#ifndef NES_EMULATOR_ADDRESSSING_MODE_H
#define NES_EMULATOR_ADDRESSSING_MODE_H

enum class addressing_mode{
    IMMEDIATE,
    ZERO_PAGE,
    ZERO_PAGE_X,
    ZERO_PAGE_Y,
    ABSOLUTE,
    ABSOLUTE_X,
    ABSOLUTE_Y,
    INDIRECT_X,
    INDIRECT_Y,
    RELATIVE,
    INDIRECT,
    NONE_ADDRESSING
};

#endif //NES_EMULATOR_ADDRESSSING_MODE_H
